# Generated by Django 4.2.2 on 2023-08-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('word', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('body', models.TextField()),
                ('keyword', models.ManyToManyField(related_name='tweet', to='backend.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField()),
                ('keywords', models.ManyToManyField(related_name='profile', to='backend.keyword')),
                ('tweets', models.ManyToManyField(related_name='profile', to='backend.tweet')),
            ],
        ),
    ]
