# Generated by Django 4.2.2 on 2023-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
