# Generated by Django 4.1.7 on 2023-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_profile_visited"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyConstituency",
            fields=[
                ("num", models.IntegerField()),
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("mla", models.CharField(max_length=200)),
                ("party", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LokSabhaConstituency",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("const_no", models.IntegerField()),
                ("mp", models.CharField(max_length=200)),
                ("party", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("symbol", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
