# Generated by Django 4.2.2 on 2023-08-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_assemblyconstituency_loksabhaconstituency_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('query', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('options', models.ManyToManyField(related_name='question', to='backend.option')),
            ],
        ),
    ]
