# Generated by Django 4.2.2 on 2023-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_question_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(related_name='quiz', to='backend.question')),
                ('users', models.ManyToManyField(related_name='quiz', to='backend.profile')),
            ],
        ),
    ]
