# Generated by Django 4.2.2 on 2023-08-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_question_options_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='questions', to='backend.option'),
        ),
    ]
